# a partir de ésa línea creo mi imagen con la versión de php y apache
FROM php:7.2-apache

# de la carpeta src  me llamas todo lo que tengo ahí, y el var, es lo que me dice la documentación 

COPY src/ /var/www/html/

# para decirle en que puerto lo tengo
EXPOSE 80